version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data_cromo:/var/lib/mysql

  web:
    build: .
    container_name: cromo
    volumes:
      - .:/workspace
      - ./staticfiles:/workspace/staticfiles
    expose:
      - 8001
    depends_on:
      - db
      - redis
    env_file:
      - .env
    restart: always
    command: >
      sh -c "python manage.py makemigrations &&
            python manage.py migrate &&
            python manage.py collectstatic --noinput &&
            gunicorn --bind 0.0.0.0:8001 cromo.wsgi:application"


  celery:
    build: .
    container_name: cromo_celery
    volumes:
      - .:/workspace
    depends_on:
      - web
      - redis
    env_file:
      - .env
    restart: always
    command: >
      sh -c '
        until nc -z redis 6379; do
          echo "Waiting for Redis...";
          sleep 2;
        done;
        celery -A cromo worker --concurrency=1 --loglevel=info
      '

  celery-beat:
    build: .
    container_name: cromo_celery_beat
    volumes:
      - .:/workspace
    depends_on:
      - web
      - redis
    env_file:
      - .env
    restart: always
    command: >
      sh -c '
        until nc -z redis 6379; do
          echo "Waiting for Redis...";
          sleep 2;
        done;
        celery -A cromo worker --concurrency=1 --loglevel=info
      '

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./staticfiles:/workspace/staticfiles
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
    # entrypoint: >
    #   /bin/sh -c '
    #   until curl -f http://web:8001/health/; do
    #     echo "Waiting for Django...";
    #     sleep 3;
    #   done;
    #   nginx -g "daemon off;";
    #   '

  minio:
    image: minio/minio@sha256:a1ea29fa28355559ef137d71fc570e508a214ec84ff8083e39bc5428980b015e
    container_name: minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    ports:
      - "9001:9001"
      - "9000:9000" # MinIO server API
    volumes:
      - minio_data:/data

  createbuckets:
    image: minio/mc@sha256:aead63c77f9db9107f1696fb08ecb0faeda23729cde94b0f663edf4fe09728e3
    depends_on:
      - minio
    env_file:
      - .env
    entrypoint: >
      /bin/sh -c '
      until /usr/bin/mc config host add myminio http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD}; do
        echo "Waiting for MinIO to be ready...";
        sleep 3;
      done;
      /usr/bin/mc mb --quiet myminio/${AWS_STORAGE_BUCKET_NAME} || true;
      /usr/bin/mc policy set none myminio/${AWS_STORAGE_BUCKET_NAME} || true;
      '
    
  # ai_training:
  #   build: ../AI_classification/training
  #   container_name: ai_training
  #   environment:
  #     - PYTHONUNBUFFERED=1
  #   env_file:
  #     - .env
  #   gpus: all
  #   user: root
  #   ports:
  #     - "8090:8090"

  # ai_inference:
  #   image: cromo_ai_classification:inference
  #   container_name: ai_inference
  #   environment:
  #     - PYTHONUNBUFFERED=1
  #   env_file:
  #     - .env
  #   gpus: all
  #   user: root
  #   ports:
  #     - "8050:8050"


volumes:
  mysql_data_cromo:
  minio_data: