worker_processes 1;

events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    proxy_set_header X-Forwarded-Proto $scheme;
    
    server {
        listen 80;
        server_name cromo.di.unisa.it;

        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
            try_files $uri =404;
        }

        location / {
            return 301 https://$host$request_uri;
        }

    }

    server {
        listen 443 ssl;
        server_name cromo.di.unisa.it;

        ssl_certificate /etc/letsencrypt/live/cromo.di.unisa.it/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/cromo.di.unisa.it/privkey.pem;

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;

        client_max_body_size 50G;

        location /static/ {
            alias /workspace/staticfiles/;
            autoindex on;
            access_log on;
            expires 1y;
            add_header Cache-Control "public";
            add_header Access-Control-Allow-Origin *;
        }

        location / {
            proxy_pass http://web:8001;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /proxy-id-cromopoi/ {
            proxy_pass http://web:8001;
        }

    }

}










### For developement 
###
###

# worker_processes 1;

# events {
#     worker_connections 1024;
# }

# http {
#     include       mime.types;
#     default_type  application/octet-stream;
#     server {
#         listen 80;
#         client_max_body_size 10G;

#         # location /.well-known/acme-challenge/ {
#         #     root /var/www/certbot;
#         #     try_files $uri =404;
#         # }

#         proxy_set_header X-Forwarded-Proto $scheme;

#         location /static/ {
#             alias /workspace/staticfiles/;
#             autoindex on;
#             access_log on;
#             expires 1y;
#             add_header Cache-Control "public";
#         }

#         location / {
#             proxy_pass http://web:8001;
#             proxy_set_header Host $host;
#             proxy_set_header X-Real-IP $remote_addr;
#             proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#             proxy_set_header X-Forwarded-Proto $scheme;
#         }

#         location /proxy-id-cromopoi/ {
#             proxy_pass http://web:8001/proxy-id-cromopoi/;
#         }
#     }
# }
