# Generated by Django 5.2 on 2025-05-08 07:50

import cromo_core.models
import django.db.models.deletion
import location_field.models.plain
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tag',
                'db_table': 'Tag',
            },
        ),
        migrations.CreateModel(
            name='Cromo_POI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('READY', 'Ready'), ('FAILED', 'Failed'), ('BUILDING', 'Building'), ('BUILT', 'Built'), ('SERVING', 'Serving'), ('ENQUEUED', 'Enqueued')], default='READY', max_length=20)),
                ('location', location_field.models.plain.PlainLocationField(blank=True, max_length=63, null=True)),
                ('build_started_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cromo POI',
                'verbose_name_plural': 'Cromo POIs',
                'db_table': 'Cromo_POI',
                'permissions': [('can_create_cromo_poi', 'Can create cromo_poi'), ('can_view_cromo_poi', 'Can view cromo_poi')],
            },
        ),
        migrations.CreateModel(
            name='Cromo_View',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('crowsourced', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('model_path', models.CharField(blank=True, max_length=200, null=True)),
                ('build_started_at', models.DateTimeField(blank=True, null=True)),
                ('default_image', models.ImageField(blank=True, null=True, storage=cromo_core.models.MinioStorage(), upload_to=cromo_core.models.default_image)),
                ('cromo_poi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cromo_core.cromo_poi')),
            ],
            options={
                'verbose_name': 'Cromo View',
                'verbose_name_plural': 'Cromo Views',
            },
        ),
        migrations.CreateModel(
            name='Cromo_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, storage=cromo_core.models.MinioStorage(), upload_to=cromo_core.models.upload_to_poi)),
                ('cromo_view', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cromo_core.cromo_view')),
            ],
        ),
    ]
