# Generated by Django 5.2.1 on 2025-05-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cromo_core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cromo_view',
            name='model_path',
        ),
        migrations.AddField(
            model_name='cromo_poi',
            name='model_path',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
