# Generated by Django 5.2.5 on 2025-09-01 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cromo_core', '0002_remove_cromo_view_model_path_cromo_poi_model_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='cromo_poi',
            name='place',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
