# Generated by Django 5.2.5 on 2025-09-01 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cromo_core', '0003_cromo_poi_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cromo_poi',
            name='place',
        ),
    ]
