# Generated by Django 5.2.5 on 2025-09-01 12:02

import cromo_core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cromo_core', '0004_remove_cromo_poi_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='cromo_poi',
            name='default_image',
            field=models.ImageField(blank=True, null=True, storage=cromo_core.models.MinioStorage(), upload_to='default_image'),
        ),
        migrations.AddField(
            model_name='cromo_poi',
            name='external_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
