# Generated by Django 5.2.5 on 2025-09-01 12:04

import cromo_core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cromo_core', '0005_cromo_poi_default_image_cromo_poi_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cromo_poi',
            name='default_image',
            field=models.ImageField(blank=True, null=True, storage=cromo_core.models.MinioStorage(), upload_to=cromo_core.models.default_image_poi),
        ),
    ]
