# Generated by Django 5.2.5 on 2025-09-03 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cromo_core', '0006_alter_cromo_poi_default_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cromo_poi',
            name='external_id',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
